on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Compile and Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        rust:
          - nightly
          - stable
          - 1.70.0
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4      
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      # TODO: enable once the differences are resolved
      #- name: cargo fmt --check
      #  run: cargo fmt --check
      - run: cargo check
      - run: cargo build

